/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PecasRouteImport } from './routes/pecas'
import { Route as NovoRouteImport } from './routes/novo'
import { Route as IaRouteImport } from './routes/ia'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrcamentoIdRouteImport } from './routes/orcamento.$id'
import { Route as ApiVozOrcamentoRouteImport } from './routes/api/voz-orcamento'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const PecasRoute = PecasRouteImport.update({
  id: '/pecas',
  path: '/pecas',
  getParentRoute: () => rootRouteImport,
} as any)
const NovoRoute = NovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentoIdRoute = OrcamentoIdRouteImport.update({
  id: '/orcamento/$id',
  path: '/orcamento/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVozOrcamentoRoute = ApiVozOrcamentoRouteImport.update({
  id: '/api/voz-orcamento',
  path: '/api/voz-orcamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/checklist': typeof ChecklistRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRoute
  '/ia': typeof IaRoute
  '/novo': typeof NovoRoute
  '/pecas': typeof PecasRoute
  '/api/chat': typeof ApiChatRoute
  '/api/voz-orcamento': typeof ApiVozOrcamentoRoute
  '/orcamento/$id': typeof OrcamentoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/checklist': typeof ChecklistRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRoute
  '/ia': typeof IaRoute
  '/novo': typeof NovoRoute
  '/pecas': typeof PecasRoute
  '/api/chat': typeof ApiChatRoute
  '/api/voz-orcamento': typeof ApiVozOrcamentoRoute
  '/orcamento/$id': typeof OrcamentoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/checklist': typeof ChecklistRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/historico': typeof HistoricoRoute
  '/ia': typeof IaRoute
  '/novo': typeof NovoRoute
  '/pecas': typeof PecasRoute
  '/api/chat': typeof ApiChatRoute
  '/api/voz-orcamento': typeof ApiVozOrcamentoRoute
  '/orcamento/$id': typeof OrcamentoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalogo'
    | '/checklist'
    | '/configuracoes'
    | '/historico'
    | '/ia'
    | '/novo'
    | '/pecas'
    | '/api/chat'
    | '/api/voz-orcamento'
    | '/orcamento/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/checklist'
    | '/configuracoes'
    | '/historico'
    | '/ia'
    | '/novo'
    | '/pecas'
    | '/api/chat'
    | '/api/voz-orcamento'
    | '/orcamento/$id'
  id:
    | '__root__'
    | '/'
    | '/catalogo'
    | '/checklist'
    | '/configuracoes'
    | '/historico'
    | '/ia'
    | '/novo'
    | '/pecas'
    | '/api/chat'
    | '/api/voz-orcamento'
    | '/orcamento/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogoRoute: typeof CatalogoRoute
  ChecklistRoute: typeof ChecklistRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  HistoricoRoute: typeof HistoricoRoute
  IaRoute: typeof IaRoute
  NovoRoute: typeof NovoRoute
  PecasRoute: typeof PecasRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiVozOrcamentoRoute: typeof ApiVozOrcamentoRoute
  OrcamentoIdRoute: typeof OrcamentoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pecas': {
      id: '/pecas'
      path: '/pecas'
      fullPath: '/pecas'
      preLoaderRoute: typeof PecasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novo': {
      id: '/novo'
      path: '/novo'
      fullPath: '/novo'
      preLoaderRoute: typeof NovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamento/$id': {
      id: '/orcamento/$id'
      path: '/orcamento/$id'
      fullPath: '/orcamento/$id'
      preLoaderRoute: typeof OrcamentoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voz-orcamento': {
      id: '/api/voz-orcamento'
      path: '/api/voz-orcamento'
      fullPath: '/api/voz-orcamento'
      preLoaderRoute: typeof ApiVozOrcamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogoRoute: CatalogoRoute,
  ChecklistRoute: ChecklistRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  HistoricoRoute: HistoricoRoute,
  IaRoute: IaRoute,
  NovoRoute: NovoRoute,
  PecasRoute: PecasRoute,
  ApiChatRoute: ApiChatRoute,
  ApiVozOrcamentoRoute: ApiVozOrcamentoRoute,
  OrcamentoIdRoute: OrcamentoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
